### ISSUE TITLE
Add this to MELPA or Marmalade or similar

### ISSUE THREAD

**Issue by wakatara** [saf-dmitry/taskpaper-mode#1]
First off, this looks *amazing*. I'm just about to install it but am seriously impressed at the amount of work you look to have done here. In fact, between this, Deft, and a few other emacs tools, I'm looking at moving over to emacs instead of my venerable vim (and fact, I could ditch more than a few gui tools and have this work cross platform.).

Could you add it to one of the emacs repositories, however? 

Great work. Really looking forward to seeing if this will replace the OSX-specific app for me, particularly as I'm looking to move back to linux.

**Comment by saf-dmitry** [comment]
Thank you for your suggestion. My plan is to add the project to the MELPA (or Marmalade) as soon as it will rich the release status.
