### ISSUE TITLE
Undo taskpaper-narrow-to-subtree?

### ISSUE THREAD

**Issue by ugurtarlig** [saf-dmitry/taskpaper-mode#11]
First of: Excellent package! Love it! 

I would love to use hoisting via

`C-c #:  Narrow buffer to the subtree under cursor (taskpaper-narrow-to-subtree).`

but I can't figure out how to undo this.

How can I get out of narrowing to subtree?

Neither work: 
- `C-c *`
- `C-c a`
- `C-c z`

**Comment by saf-dmitry** [comment]
See #9. I've also updated documentation to include this information.
