### ISSUE TITLE
Pressing C-c C-c clears the query string (not working)

### ISSUE THREAD

**Issue by ugurtarlig** [saf-dmitry/taskpaper-mode#12]
`Pressing C-c C-c clears the query string` does not work for me.

Also, `M-x taskpaper-occur-remove-highlights` does not clear the search. 

Need to do `C-c C-q`, then `RET` to submit an empty search to clear search.

**Comment by saf-dmitry** [comment]
Sorry, I cannot reproduce this, but I think you just misunderstood the meaning of `C-c C-c`.

`C-c C-c` is bound to `taskpaper-occur-remove-highlights` _only in a TaskPaper mode buffer_ and removes highlights from the `taskpaper-occur` command.

In query and I-query mode `C-c C-c` clears (= deletes) query string _in minibuffer_ where you enter your query. It does not "clear the search", i.e. folded view with search results. To see all items after a search use `C-c C-a` or `ESC ESC` (`taskpaper-outline-show-all`).
