### ISSUE TITLE
About shortcut key.

### ISSUE THREAD

**Issue by flyingns** [saf-dmitry/taskpaper-mode#13]
For example, today is `2021-02-04`. I entered `due(%%+2d)`. What shortcut key can I press to expand it to a display format like `@due(2021-02-06)`?

**Comment by saf-dmitry** [comment]
Sorry, the date expansion is intended to work only as part of tag fast-selection. I've updated the documentation to state it more clearly.

For example, you often need to schedule tasks, which should be accomplished in one week. You can add the corresponding entry to the `taskpaper-tag-alist` user option:

    (setq taskpaper-tag-alist '(("due(%%+1w)" . ?d)))

Then, every time you want to schedule a "one-week task", you press `C-c @` followed by `d` to select the tag in the fast-selection dialog. The `@due` tag with the date expanded will be inserted at the cursor position in the main window.

**Comment by flyingns** [comment]
OK, thank you very much for your answer.
