### ISSUE TITLE
How to do structured search like XPath？

### ISSUE THREAD

**Issue by flyingns** [saf-dmitry/taskpaper-mode#14]
Taskpaper client search syntax, such as this:

`project *//not @done，`

or slice syntax,

`[start:end]`  // slices from start to end - 1

How is it done?

**Comment by saf-dmitry** [comment]
From README:

> Note: Though the query language syntax described here represents a valid subset of search syntax implemented in TaskPaper v3 app (with some minor exceptions), the search behavior is slightly different. TaskPaper mode does not support the item path syntax and set operations in search queries evaluating tag inheritance instead.

> If an item has a certain tag, all its subitems will inherit that tag. To limit tag inheritance to specific tags, configure the user option `taskpaper-tags-exclude-from-inheritance`.

Slices are set operations and thus not supported.

This has both advantages as well as disadvantages comparing to the TaskPaper's item path syntax. If you can not figure out how to formulate search query while searching for specific items, let me know.

**Comment by flyingns** [comment]
So, if I have such two projects, which have some items,

```
Project 1:
    -task 1 @done
    -task 2
    -task 3
Project 2:
    -task 1
    -task 2
    -task 3
```

What syntax can be used to make the filtered results only display the first item of the unfinished items of each project, that is, this content:

```
Project 1:
    -task 2
Project 2:
    -task 1
```

Thanks a lot.

**Comment by saf-dmitry** [comment]
I would suggest adding a tag like `@na` to the next action items in each project and searching for them later:

    @na and not @done

You can add `na` to the `taskpaper-tags-to-remove-when-done` variable, so it will be removed automatically once the item is completed:

    (setq taskpaper-tags-to-remove-when-done '("na"))

**Comment by flyingns** [comment]
Although it is a bit troublesome, it can temporarily solve the problem. :-(

Thanks a lot.
