### ISSUE TITLE
moving and tagging with "project"

### ISSUE THREAD

**Issue by peterjbraam** [saf-dmitry/taskpaper-mode#2]
First of all - it's wonderful to see this emacs package being actively maintained.  Many thanks.

One of the nice features of TaskPaper on MacOS is to archive tasks and append a @project tag to the task that has the "base-name" (all projects that are ancestors in order).

Another useful function using "projects" (I think project names are likely the names non-leaf nodes) is "move selection to project". 

I think there is probably a fairly easy way to write a few functions that append project tags, or take project names as arguments when moving selections to projects (ideally offering projects to select from while doing so).  Can this easily be added?  How?

**Comment by saf-dmitry** [comment]
Both archiving and refiling features are already implemented in TaskPaper mode and extensively documented. For more details see README.md.

# Archiving

The command `C-c C-x a` (`taskpaper-archive-subtree`) archives the subtree starting at the cursor position to the location given by `taskpaper-archive-location`. The default archive location is a file in the same directory as the current file, with the name derived by appending `_archive.taskpaper` to the current file name without extension. You can also choose what item to file archived items under. For details see the documentation string of the variable `taskpaper-archive-location`. The subtree is filed below the target item as a subitem. Depending on `taskpaper-reverse-note-order`, it will be either the first or last subitem.

When the `taskpaper-archive-save-context` custom option is non-nil, a `@project` tag with project hierarchy is added to the archived item.

# Refiling

The following special commands can be used to move/copy subtree under cursor to other location:

 - `C-c C-w`: Move the subtree under cursor to different (possibly invisible) location (`taskpaper-refile-subtree`).

 - `C-c M-w`: Copy the subtree under cursor to different (possibly invisible) location (`taskpaper-refile-subtree-copy`).

This commands prompt the user for an outline path to an item offering standard minibuffer completion for possible target locations. Special completion packages like [Ivy][emacs-ivy] or [Icicles][emacs-icicles] provide faster and more convenient way to complete the outline path in minibuffer. This is the interface also used by the `C-c C-j` goto command.

The subtree is filed below the target item as a subitem. Depending on `taskpaper-reverse-note-order`, it will be either the first or last subitem.

[emacs-ivy]: https://github.com/abo-abo/swiper

[emacs-icicles]: https://www.emacswiki.org/emacs/Icicles
