### ISSUE TITLE
C-c  C-d: put date time

### ISSUE THREAD

**Issue by avelino** [saf-dmitry/taskpaper-mode#5]
today put date (now), It would be interesting to put date and time

**Comment by saf-dmitry** [comment]
Now the user option `taskpaper-complete-save-date` accepts `'date` and `'time` values, so if you want to add date and time to the `@done` tag, customize the `taskpaper-complete-save-date` variable accordingly:
````elisp
(setq taskpaper-complete-save-date 'time)
````
