### ISSUE TITLE
Please don't bundle third-party libraries

### ISSUE THREAD

**Issue by tarsius** [saf-dmitry/taskpaper-mode#6]
Please remove `adaptive-wrap.el`. While Melpa does not include that file in the `taskpaper-mode`, some users install packages by cloning their Git repository. It `adaptive-wrap` is also installed explicitly and separately, then it is undefined which version gets loaded (depending on the order of the `load-path`). That is a problem because your copy might not include the very latest upstream changes.

**Comment by saf-dmitry** [comment]
Actually, the version of  `adaptive-wrap.el` included in this repository is an _adapted_ version, which _supports tabs_, _works on one-line paragraphs_, and can be used in modes other than TaskPaper mode. Therefore I include it in this repository 

I will probably rename it and host on its own GitHub repository, which will be mentioned here. Suggestions are always welcome.

**Comment by tarsius** [comment]
`adapted-adaptive-warp`, or `adapted-wrap` for short :wink:

But before you think about finalizing the fork, you should try to get your changes merged into the original project.

**Comment by saf-dmitry** [comment]
> you should try to get your changes merged into the original project

Yes, that is my plan.

**Comment by tarsius** [comment]
Friendly ping!

**Comment by saf-dmitry** [comment]
I recently got feedback from Stefan Monnier, one of the developer of `adaptive-wrap.el` concerning my patches and suggestions. There are still some open points to discuss.

**Comment by tarsius** [comment]
Thanks!
