### ISSUE TITLE
taskpaper-refile-subtree: Wrong type argument: listp

### ISSUE THREAD

**Issue by morewithout** [saf-dmitry/taskpaper-mode#8]
Hi,

First off. Thank you so much for taskpaper-mode. I love it!

Now. I'm having problems with taskpaper-refile-subtree (C-c C-w). It fails immediately after selecting the target as follows:

> Get targets...done
> funcall-interactively: Wrong type argument: listp, 32

I'm not using any special completion packages (I was using Helm but the problem persists after removing it completely). 

taskpaper-goto (C-c C-j) works fine.

TIA,

Mark

**Comment by saf-dmitry** [comment]
Sorry for breaking things in between and thank you for finding it out. Now refiling should wok as expected.

**Comment by morewithout** [comment]
Thanks for fixing this so quickly :-)
